export {Hero} from './hero/hero'
export {CursosBanner} from './cursosbanner/cursos-banner'
export {PublicacionesCarousel} from './publicacionescarousel/publicaciones-carousel'
export {SobreMi} from './sobremi/sobremi'
export {FixedButton} from './affix/affix'
export {Contacto} from './contacto/contacto'